### ISSUE TITLE
docker pull leads to EOF error

### ISSUE THREAD

**Issue by pmayer** [docker/for-linux#1125]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior

`docker pull` should pull the image

### Actual behavior

`docker pull` leads to EOF error, e.g.:

```
docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
df8698476c65: Pulling fs layer 
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/68/6858809bf669cc5da7cb6af83d0fae838284d12e1be0182f92f6bd96559873e3/data?verify=1602242191-QAKuEm%2BHnk6NqmQt0M7VpscMvAI%3D: EOF
```
### Steps to reproduce the behavior

install docker `5:19.03.9~3-0~debian-stretch` or above and use docker pull
(`5:19.03.8~3-0~debian-stretch` works as intended).

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:24:16 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:22:48 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 92
 Server Version: 19.03.9
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.0-12-amd64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.859GiB
 Name: ***
 ID: ***
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by pmayer** [comment]
Never mind – seems to be a FortiGate issue.

**Comment by natiT** [comment]
Hey @pmayer we just have the same issue and changed to a FortiGate. What exactly did you configure in your fortigate to get this working? :)

**Comment by jackie-ak** [comment]
Hi @natiT , I was also involved in debugging this issue, and inspecting the TLS handshake lead us to believe that something in the connection just gets dropped. After some cooperative debugging session with our NOC team we found out that the FortiGate seems to just drop the TLS packets on the outbound interface without any logging or notification. The whole thing seems to have been introduced with an update of the FortiGate firmware in September (although I do not know which update it was exactly). I think what the NOC then did was to use a different TLS inspection policy, which solved the issue for us. But I'll point them to this thread, maybe they can tell you more.

**Comment by natiT** [comment]
TLS Inspection is a good hint. I will do a research on this tomorrow :)

**Comment by jackie-ak** [comment]
Got back some more details. The issue ocured after an upgrade to firmware 6.2.5. After they disabled TLS inspection in a rule that applied for our docker host machine (which in turn was a VM), everything worked. In the meantime they are at a newer release but we did not test yet if this bug is already resolved.

**Comment by natiT** [comment]
Sorry for the late Response. I did to tests: 

First Test: All our Clients can talk to docker.io and docker.com with no TLS Inspection. Problem was not resolved. 
Second Test: All Servers with docker can Talk to "ALL" with no TLS Inspection. Problem not resolved.

Maybe we have another problem i will do a research on that. :)
