### ISSUE TITLE
18.09: containerd depends on overlay

### ISSUE THREAD

**Issue by ikus060** [docker/for-linux#475]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
installing docker using `curl -s https://get.docker.com/ | sh` should work in all common environment.

### Actual behavior
Making use of `curl -s https://get.docker.com/ | sh` when the overlay driver cannot be used doesn't allow docker service to be started.

### Steps to reproduce the behavior

After installing, I need to manually edit the containerd.service to remove the following line: 
```
ExecStartPre=/sbin/modprobe overlay
```

**Comment by geonunez** [comment]
Today I upgraded a server thats run **Debian 9.5** (_Stretch_) and apt said that a new docker's version was available with the label 5:18.09.0~3-0~debian-stretch

After applied the upgrade docker did can't start, because '**modprobe overlay**' was failing.

I didn't find how to fixed and I installed the previous docker's version that is '18.06.1~ce~3-0~debian' and everything works again.

**Comment by thaJeztah** [comment]
ping @seemethere @crosbymichael

**Comment by andrewhsu** [comment]
Hmm...I believe we're good on stock kernel that comes with Debian Stretch. Custom kernels will need `overlay` kernel module to be avail. Digging a little on google i see this discussion on Linode kernel modules for docker: https://www.linode.com/community/questions/17114/docker-wont-start-using-the-latest-linode-kernel

I'm not a user of Linode nor do we support that env when building the docker-ce packages for testing, but that thread may be a place to start.

**Comment by ikus060** [comment]
> Hmm...I believe we're good on stock kernel that comes with Debian Stretch. Custom kernels will need overlay kernel module to be avail.

Problem is not related to the kernel we are running. I'm running "stock" kernel, but overlay module could not be used because we are not using xfs or ext4. For that reason, overlay is not loaded and only aufs is loaded.

**Comment by geonunez** [comment]
@andrewhsu It was a excellent start,

I changed the linode's kernel to the generic one and docker's latest seems to works without problems.

Thanks for the help guys.

**Comment by onlime** [comment]
Same here, we are unable to use `overlay` as we run Docker in an LXC container which runs on zfs (ZFSonLinux). We have mounted an external `btrfs` volume as `/var/lib/docker` inside LXC container and set Docker's storage-driver to btrfs via `/etc/docker/daemon.json`:

```json
{
  "storage-driver": "btrfs"
}
```

This works all nicely, but since upgrading to **Docker 18.09 (18.09.0~3-0~debian-stretch)** and its introduction/dependency of containerd.io, it won't start up. Commenting out that line in `/lib/systemd/system/containerd.service` does the trick, but seems like a dirty workaround:

```
#ExecStartPre=/sbin/modprobe overlay
```

Any idea of how to fix this in a clean way?
Should we mount some extra volume for containerd and also let it use `btrfs` storage driver?

**Comment by lbschenkel** [comment]
Got bitten by this as well, reported to upstream: https://github.com/containerd/containerd/issues/2772

**Comment by thaJeztah** [comment]
>  I thought of doing that, but my understanding is that you cannot override ExecStartPre= via a systemd drop-in file because this entry can be specified multiple times

I think the trick there (similar to `ExecStart`) is (if you want to _replace_ the option) to first _reset_ the option, then specify the new one. So;

### To add an extra `ExecStartPre`;

```
[Service]
ExecStartPre=echo hello world
```

Will result in

```
[Service]
ExecStartPre=/sbin/modprobe overlay
ExecStartPre=echo hello world
```

### To reset / remove the `ExecStartPre`

```
[Service]
ExecStartPre=
```

Will result in the `ExecStartPre` to be removed

```
[Service]
```

### To replace / override the `ExecStartPre`

Effectively a combination of the above; first reset the existing one, and immediately set the new one;

```
[Service]
ExecStartPre=
ExecStartPre=echo hello world
```

Will result in

```
[Service]
ExecStartPre=echo hello world
```


(at least I think that's how it works; didn't try)

**Comment by cpuguy83** [comment]
Seems like this should be ignoring errors from modprobe.

**Comment by lbschenkel** [comment]
Agreed, at the very least
```
ExecStartPre=-/sbin/modprobe overlay
```
Would already be a solution. (Errors are ignored when the command starts with `-`.)

**Comment by onlime** [comment]
@thaJeztah Thanks so much for your very detailed and perfectly clear instructions! I though about using Systemd `override.conf` instead of patching `containerd.service` but didn't know about that option of resetting `ExecStartPre` which can be specified multiple times.

Your solution works perfectly, tested (by `systemctl show containerd.service | grep ExecStartPre` and by restarting the service).

```ini
# /etc/systemd/system/containerd.service.d/override.conf
[Service]
ExecStartPre=
```

Confirmed working 100%.
So now let's wait for upstream to fix this. Hopefully we can use the new `docker engine activate` feature without the overlay requirement.

**Comment by jdespatis** [comment]
@thaJeztah Thanks a lot for your workaround, it works like a charm with my Ubuntu 16.05.5 LTS !

**Comment by geerlingguy** [comment]
I've run into this error when running some tests installing Docker-in-Docker on Travis CI on Debian 9, Ubuntu 18.04, CentOS 7, and Ubuntu 16.04 too (see related: https://github.com/geerlingguy/ansible-role-docker/issues/97).

It looks like this was fixed in the `containerd` project here: https://github.com/containerd/containerd/pull/2776

Is there a timeline for the next Docker package release? Or should I build in the hack to override the `ExecStartPre` command on all my builds for the forseeable future? Right now I can't get Docker to start in many of my regular build environments using the instructions in Docker's docs (and same for tons of my downstream users).

**Comment by thaJeztah** [comment]
The same fix as was merged in containerd has been merged in the packaging repository, but I don't have an ETA for when updated packages will be available.

**Comment by geerlingguy** [comment]
So for now, the fix is:

Add a new file with the `ExecStartPre` override:

```
sudo mkdir -p /etc/systemd/system/containerd.service.d
sudo nano /etc/systemd/system/containerd.service.d/override.conf
```

Contents of `override.conf`:

```
[Service]
ExecStartPre=
```

Reload the systemctl daemon:

```
$ sudo systemctl daemon-reload
```

Now you can start Docker successfully (`sudo systemctl start docker`).

**Comment by ericsysmin** [comment]
Ha, geerling, I've been trying to fix this the past 3 days as well....closest I got was figuring out overlay was the problem

**Comment by aMozejko1** [comment]
Not sure if the same issue but I fixed by symlinking the /lib/systemd/system/docker.service to /etc/systemd/system.

Also don't know if it's because I'm doing something wrong or not but installing 18.09 on UB16 didn't seem to install a docker binary?

sudo apt-get install docker-ce=18.06.1~ce~3-0~ubuntu
sudo apt-get install docker-ce=5:18.09.0~3-0~ubuntu-xenial 
cd /etc/systemd/system                                                
sudo mv docker.service _docker.service                                
sudo ln -s /lib/systemd/system/docker.service docker.service          
sudo systemctl daemon-reload                                          
sudo service docker start                                             
docker version

Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:57 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by hswong3i** [comment]
Upstream PR get merged, see https://github.com/containerd/containerd/pull/2776

**Comment by toddpi314** [comment]
@aMozejko1's fix confirmed working on PixelBook i7 ChromeOS 70.0.3538.76 (crostini Penguin container). Thank you sir.

**Comment by RobertLHarris** [comment]
No go for me with @aMozejko1's version.  I still get a message docker.service couldn't start due to a dependancy job.

**Comment by priyanka19-98** [comment]
> So for now, the fix is:
> 
> Add a new file with the `ExecStartPre` override:
> 
> ```
> sudo mkdir -p /etc/systemd/system/containerd.service.d
> sudo nano /etc/systemd/system/containerd.service.d/override.conf
> ```
> 
> Contents of `override.conf`:
> 
> ```
> [Service]
> ExecStartPre=
> ```
> 
> Reload the systemctl daemon:
> 
> ```
> $ sudo systemctl daemon-reload
> ```
> 
> Now you can start Docker successfully (`sudo systemctl start docker`).

Hi @geerlingguy , the above steps didn't, work for me, still getting 
```
[pjiandan@pjiandan ~]$ sudo systemctl daemon-reload
[pjiandan@pjiandan ~]$ sudo systemctl start docker
A dependency job for docker.service failed. See 'journalctl -xe' for details.
```

**Comment by thaJeztah** [comment]
@priyanka19-98 unfortunately the default output of systemd on failure is usually not very useful. You can try;

```
sudo journalctl -xu docker.service

# or, to get the last 50 entries;
sudo journalctl -n 50 -xu docker.service
```

or 

```
sudo journalctl -xu containerd.service
```

To get the logs of docker or containerd, which probably have more details

**Comment by priyanka19-98** [comment]
@thaJeztah  the logs:
```
-- Logs begin at Sat 2020-09-19 13:15:01 IST, end at Thu 2020-10-01 17:47:45 IST. --
Oct 01 17:07:05 pjiandan.remote.csb systemd[1]: Dependency failed for Docker Application Container Engin>
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit docker.service has failed.
-- 
-- The result is RESULT.
Oct 01 17:07:05 pjiandan.remote.csb systemd[1]: docker.service: Job docker.service/start failed with res>
Oct 01 17:07:05 pjiandan.remote.csb systemd[1]: Dependency failed for Docker Application Container Engin>
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit docker.service has failed.
-- 
-- The result is RESULT.
Oct 01 17:07:05 pjiandan.remote.csb systemd[1]: docker.service: Job docker.service/start failed with res>
Oct 01 17:07:05 pjiandan.remote.csb systemd[1]: Dependency failed for Docker Application Container Engin>
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit docker.service has failed.
-- 
-- The result is RESULT.
Oct 01 17:07:05 pjiandan.remote.csb systemd[1]: docker.service: Job docker.service/start failed with res>
Oct 01 17:23:52 pjiandan.remote.csb systemd[1]: Dependency failed for Docker Application Container Engin>
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit docker.service has failed.
-- 
-- The result is RESULT.
Oct 01 17:23:52 pjiandan.remote.csb systemd[1]: docker.service: Job docker.service/start failed with res>
Oct 01 17:24:59 pjiandan.remote.csb systemd[1]: Dependency failed for Docker Application Container Engin>
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit docker.service has failed.
-- 
-- The result is RESULT.
Oct 01 17:24:59 pjiandan.remote.csb systemd[1]: docker.service: Job docker.service/start failed with res>
Oct 01 17:24:59 pjiandan.remote.csb systemd[1]: Dependency failed for Docker Application Container Engin>
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
lines 1-49
```

**Comment by thaJeztah** [comment]
@priyanka19-98 did you use `journalctl -xu <service name>` ? those don't look like the logs from docker or containerd

**Comment by priyanka19-98** [comment]
@thaJeztah  yes these are the logs of `sudo journalctl -xu docker.service`

**Comment by priyanka19-98** [comment]
Output for `sudo journalctl -xu containerd.service`

```
[pjiandan@pjiandan ~]$ sudo journalctl -xu containerd.service
-- Logs begin at Sat 2020-09-19 13:15:01 IST, end at Fri 2020-10-02 00:24:08 IST. --
Oct 01 14:27:30 pjiandan.remote.csb systemd[1]: Starting containerd container runtime...
-- Subject: Unit containerd.service has begun start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit containerd.service has begun starting up.
Oct 01 14:27:30 pjiandan.remote.csb containerd[6711]: /usr/bin/containerd: symbol lookup error: /usr/bin/containerd: undefined symbol: seccomp_api_set
Oct 01 14:27:30 pjiandan.remote.csb systemd[1]: containerd.service: Main process exited, code=exited, status=127/n/a
Oct 01 14:27:30 pjiandan.remote.csb systemd[1]: containerd.service: Failed with result 'exit-code'.
Oct 01 14:27:30 pjiandan.remote.csb systemd[1]: Failed to start containerd container runtime.
-- Subject: Unit containerd.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit containerd.service has failed.
-- 
-- The result is RESULT.
Oct 01 14:27:30 pjiandan.remote.csb systemd[1]: containerd.service: Service RestartSec=100ms expired, scheduling restart.
Oct 01 14:27:30 pjiandan.remote.csb systemd[1]: containerd.service: Scheduled restart job, restart counter is at 1.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Automatic restarting of the unit containerd.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Oct 01 14:27:30 pjiandan.remote.csb systemd[1]: Stopped containerd container runtime.
-- Subject: Unit containerd.service has finished shutting down
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit containerd.service has finished shutting down.
Oct 01 14:27:30 pjiandan.remote.csb systemd[1]: Starting containerd container runtime...
-- Subject: Unit containerd.service has begun start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit containerd.service has begun starting up.
Oct 01 14:27:30 pjiandan.remote.csb containerd[6723]: /usr/bin/containerd: symbol lookup error: /usr/bin/containerd: undefined symbol: seccomp_api_set
Oct 01 14:27:30 pjiandan.remote.csb systemd[1]: containerd.service: Main process exited, code=exited, status=127/n/a
Oct 01 14:27:30 pjiandan.remote.csb systemd[1]: containerd.service: Failed with result 'exit-code'.
Oct 01 14:27:30 pjiandan.remote.csb systemd[1]: Failed to start containerd container runtime.
-- Subject: Unit containerd.service has failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit containerd.service has failed.
-- 
-- The result is RESULT.
```
