### ISSUE TITLE
Error response from daemon ... executable file not found in $PATH"

### ISSUE THREAD

**Issue by jonathansberry** [docker/for-linux#561]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

### Expected behavior
I expect to be able to run basic containers like hello-world, python, mysql.

### Actual behavior
Every container I try to run fails with an `executable file not found in $PATH` error. It seems like the docker daemon can't find any executable.

```
jonathan@ullswater:~$ docker run hello-world
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/hello\": stat /hello: no such file or directory": unknown.
ERRO[0000] error waiting for container: context canceled 
jonathan@ullswater:~$ docker run -ti python bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown.
jonathan@ullswater:~$ docker run -ti mysql bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown.
```

If I try to build a container using a simple docker file:
```
FROM mysql
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
```
It fails to find bash to run and  create the second layer. 
```
db$ docker build .
Sending build context to Docker daemon  2.186MB
Step 1/4 : FROM mysql
 ---> 102816b1ee7d
Step 2/4 : RUN chmod +x /usr/local/bin/docker-entrypoint.sh
 ---> Running in 20d605e26091
OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
```

### Steps to reproduce the behavior
No one else in my team has this problem

**Output of `docker version`:**

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 730
Server Version: 18.09.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 758
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-141-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.647GiB
Name: ullswater
ID: E7FP:PKWC:J72F:PRNN:2E2H:TDL5:PTJ7:GAQT:YZBP:P54E:OYLG:IAYT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
Just running on my local Ubuntu 16.04.5 LTS laptop.

**Comment by jonathansberry** [comment]
Some one else in my time managed to find this issue lodged with moby:
https://github.com/moby/moby/issues/38174

It reports the same error with one respondant saying:
```Yes, you can't use slave propagation with docker version 18.09 because containerd is running in a different mount namespace.```

It reports the fix as being:
```

**Comment by gauravgemalto** [comment]
Hi I am getting error can you plese help me over this.

OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"ping\": executable file not found in $PATH": unknown

i am running 2 nginx over same network and when i am trying to ping them getting this error.

#docker container exec -it my_new_nginx ping my_nginx_1

**Comment by cpuguy83** [comment]
Please check your docker.service configuration.
If you have previously added something like `MountPropagation=slave`, this would cause issues with Docker 18.09.

You should be able to safely remove any `MountPropagation` setting.

**Comment by haydonryan** [comment]
I'm experiencing this on MacOS with Docker engine 18.09.1.  My docker advanced daemon setup is:

```{
  "experimental" : false,
  "debug" : true
}
```

As far as I know, I haven't set anything around MountPropagation. Is there somewhere else I should be checking for docker.service config? There's nothing set outside of credentials in the ~/.docker/ directory.

**Comment by cpuguy83** [comment]
@haydonran under what circumstances are you seeing this behavior?

**Comment by haydonryan** [comment]
Trying to run `docker build` after importing an image. 

I just realized that I'm posting this under for-linux - apologies.  I'll try an uninstall/reinstall and create a new issue under the for-mac.

**Comment by DrReblaus** [comment]
Hi @cpuguy83 and @jonathansberry!
I am having the same problem after new installation of docker version CE 18.09.2 on CentOS Linux release 7.6.1810 (Core)

The below run container is the centos image from the docker hub.
 
```
[root@c-localdomain]# docker run centos echo works
works
[root@c-localdomain]# docker run centos -p 9002/9002
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"-p\": executable file not found in $PATH": unknown.
ERRO[0001] error waiting for container: context canceled 
```



##### Docker Information
```
[root@c-localdomain]# docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
##### centOS information
```
cat /etc/*release
CentOS Linux release 7.6.1810 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.6.1810 (Core) 
CentOS Linux release 7.6.1810 (Core) 
```

##### docker.service file 
without any entry for Mountsflag.
[docker.service.zip](https://github.com/docker/for-linux/files/2870772/docker.service.zip)

Thank you for your help

PS: I have also installed a working nextcloud on the same machine as the docker

**Comment by cpuguy83** [comment]
> docker run centos -p 9002/9002

This command is trying to run `-p 9002/9002` in the `centos` image, which does not exist.

**Comment by marcoslneves** [comment]
I don't know why but I was able to run the container by inverting the order of the I was able to execute the container by inverting the order of the -p and container name parameters **-p** and **container name**.

_docker run  -p 8001:8001 container-name:latest_

**Comment by thaJeztah** [comment]
@marcoslneves that's unrelated; `-p` is an option for the docker command-line; those options must be put before the container name; everything after the container name is passed to the container as command (so if you put `-p` after the container name, it will attempt to run `-p` as command inside the container, which will fail)

**Comment by thaJeztah** [comment]
Looking at the discussion above, I think the original issue was resolved, so I'm closing this ticket

**Comment by AbhimanyuG** [comment]
Issue still exists in 18.09.5

**Comment by cpuguy83** [comment]
See the linked issue. Most likely the issue is you have a custom systemd configuration ("MountFlags=slave")  and its incompatible with 18.09.

**Comment by KrishnakNamburi** [comment]
The issues persists in centos and 18.9.5 . I donot see any mountflags=slave config in out systemd

Description=Docker Application Container Engine
Documentation=https://docs.docker.com
BindsTo=containerd.service
After=network-online.target firewalld.service containerd.service
Wants=network-online.target
Requires=docker.socket

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
ExecReload=/bin/kill -s HUP $MAINPID
TimeoutSec=0
RestartSec=2
Restart=always

# Note that StartLimit* options were moved from "Service" to "Unit" in systemd 229.
# Both the old, and new location are accepted by systemd 229 and up, so using the old location
# to make them work for either version of systemd.
StartLimitBurst=3

# Note that StartLimitInterval was renamed to StartLimitIntervalSec in systemd 230.
# Both the old, and new name are accepted by systemd 230 and up, so using the old name to make
# this option work for either version of systemd.
StartLimitInterval=60s

# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

# Comment TasksMax if your systemd version does not supports it.
# Only systemd 226 and above support this option.
TasksMax=infinity

# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target

**Comment by KrishnakNamburi** [comment]
I found a file **/etc/systemd/system/docker.service.d/mountflags-slave.conf**
I commented out the MountFlags

**[Service]
# MountFlags "slave" helps to prevent "device busy" errors on RHEL/CentOS 7.3 kernels
#MountFlags=slave**

And then 

**systemctl daemon-reload
systemctl restart docker**

docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

**Comment by cpuguy83** [comment]
Yes. The issue with busy errors is fixed and should not need to set the MountFlags option.

In 18.09 specifically, dockerd is no longer responsible for starting/managing containerd (which does all the work to execute the container), instead there is a new service added to systemd.
Because of this, settings like "MountFlags" or "PrivateTmp" will break things due to the fact that containerd will not be able to see mounts created by dockerd... basically these settings cause systemd to create a new mount namespace for each service.

**Comment by kylepeters** [comment]
I am following a [tutorial](https://docs.microsoft.com/en-us/dotnet/core/docker/build-container), and I am receiving this error...
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"cmd.exe\": executable file not found in $PATH": unknown.

I realize it is a pathing issue, but I am not sure how to proceed.  Any suggestions?

**Comment by thaJeztah** [comment]
Looks like you're following a tutorial for windows containers, but Docker Desktop is configured to run linux containers (you can either switch to Windows containers, or find a tutorial for dotnet Linux)

**Comment by ahmadnadzirr** [comment]
RUN ["chmod", "+x", "/usr/local/bin/docker-entrypoint.sh"] it works on me

**Comment by kylepeters** [comment]
Will that work in a Windows environment?

**Comment by dudziakm** [comment]
I closed the terminal and open again - it helped :D

**Comment by AzyCrw4282** [comment]
I encountered the same error. It turns out that I specified the wrong dir to be copied, e.g. COPY /conf/platform/startup.sh /usr/bin/
Instead of
COPY /conf/platform/startup.sh /conf/bin/
I also specified the PATH in env variables in docker file like so, 
   PATH="/conf/bin:${PATH}".

That seems have done the job.

**Comment by hayreddintuzel** [comment]
> I don't know why but I was able to run the container by inverting the order of the I was able to execute the container by inverting the order of the -p and container name parameters **-p** and **container name**.
> 
> `docker run -p 8001:8001 container-name:latest`
> 
> I'm using Engine 18.09.2
> 
> **My error message:**
> _docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: "-p": executable file not found in $PATH": unknown. ERRO[0001] error waiting for container: context canceled_

It is crazy but it works for me, too

**Comment by pruse2402** [comment]
> **SOLVED** - here's how...
> 
> Some one else in my team managed to find this issue lodged with moby:
> [moby/moby#38174](https://github.com/moby/moby/issues/38174)
> 
> It reports the same error with one respondant saying:
> `Yes, you can't use slave propagation with docker version 18.09 because containerd is running in a different mount namespace.`
> 
> It reports the fix as being:
> `I delete "MountFlags=slave" in /lib/systemd/system/docker.service. And "systemctl restart docker", all container running.`
> 
> I actually found this config param to be set elsewhere in a drop-in config file:
> `/etc/systemd/system/docker.service.d/docker.conf`
> After removing the config param, I ran `systemctl restart docker` and `systemctl daemon-reload` and had to reboot the machine to get everything working again.

How to delete MountFlags=slave?

Thanks in advance

**Comment by dmitryrn** [comment]
```docker run -p 1234:1234 2b8d0f1f07e8```

instead of

```docker run 2b8d0f1f07e8 -p 1234:1234```

**Comment by k-caps** [comment]
In my case I had been specifying `-d`  as well as `-it`, removed that and everything was fine

**Comment by Bin4xin** [comment]
@dmitryrn 他是对的。当您想要指定一些参数像`port`时应按照下面的格式：

`sudo docker run -it -d --name {name} -p 80:80 -p 3306:3306 {REPOSITORY NAME}`

**Comment by h00l00v00** [comment]
In my case i **save**d the docker image and instead of **load**ing it on the other machine i **import**ed it which are very different and lead me to an error similar to this.

**Comment by saket13** [comment]
I solved this by (MacOS)
1. Giving proper permissions - RUN ["chmod", "+x", "./entrypoint.sh"]
2. Specifying relative path of entrypoint - ENTRYPOINT ["./entrypoint.sh"] 
in Docker file and

3. Specifying port before image name - docker run -d -p 1234:1234 <app_name>:latest

**Comment by dexterzep** [comment]
> **SOLVED** - here's how...
> 
> Some one else in my team managed to find this issue lodged with moby: [moby/moby#38174](https://github.com/moby/moby/issues/38174)
> 
> It reports the same error with one respondant saying: `Yes, you can't use slave propagation with docker version 18.09 because containerd is running in a different mount namespace.`
> 
> It reports the fix as being: `I delete "MountFlags=slave" in /lib/systemd/system/docker.service. And "systemctl restart docker", all container running.`
> 
> I actually found this config param to be set elsewhere in a drop-in config file: `/etc/systemd/system/docker.service.d/docker.conf` After removing the config param, I ran `systemctl restart docker` and `systemctl daemon-reload` and had to reboot the machine to get everything working again.

for me it was pretty straight forward. Backgroud: I was getting this error while running apache ws container. I noticed that a lot of containers were running in the background occupying various ports, I killed them all and VOILA...

**Comment by stanivanovpro** [comment]
> RUN ["chmod", "+x", "/usr/local/bin/docker-entrypoint.sh"] it works on me

This helped for me. But this also helped me realise that docker-entrypoint.sh file didn't have "+x" (executable) modifier in my source code. I've decided that the right thing to do was to add this modifier to this file in my source code. After this container started working as expected with no need for chmod in Dockerfile.

**Comment by dinushaAsamarakoon** [comment]
if you use the docker desktop in windows try Reset to factory defaults in troubleshoot option.
