### ISSUE TITLE
Please provide repo for docker-ce on Fedora 30.

### ISSUE THREAD

**Issue by jhford** [docker/for-linux#600]
* [ ] This is a bug report
* [X] This is a feature request
* [ ] I searched existing issues before opening this one

The Docker-CE Fedora repository is the [recommended way](https://docs.docker.com/install/linux/docker-ce/fedora/#install-using-the-repository) to install Docker CE on Fedora.  It has many benefits over installing from a package or any other method.

Fedora also releases a new version every six months.  The Fedora repository also takes a very long time to become ready after the release of a new version, with many issues being opened after each recent Fedora is release.

Fedora has officially branched Version 30 today and might have a beta release on March 26.

I'm filing this issue to hopefully put this task on the radar, so that there might be a repository set up in time for the Fedora 30 release on April30

Release Schedule: https://fedoraproject.org/wiki/Releases/30/Schedule#Key_Milestones

**Comment by favadi** [comment]
There is test/nightly repository available for Fedora 30, but broken because containerd package is not available. Do we have plan to fix it soon?

**Comment by claysauruswrecks** [comment]
I was able to twerkaround by downloading the RPMs directly from:
https://download.docker.com/linux/fedora/30/x86_64/test/Packages/

```
sudo dnf install -y containerd
sudo dnf install -y ./docker-ce-cli-19.03.0-1.1.beta1.fc30.x86_64.rpm
sudo rpm -i --nodeps ./docker-ce-19.03.0-1.1.beta1.fc30.x86_64.rpm
```

**Comment by wohlben** [comment]
its technically also possible to just install the fedora29 versions by hardcoding the $releasever to 29 in the repository file.

should only be done *temporarily* for one installation as it will create issues with updates later on. 

```
[docker-ce-stable]
name=Docker CE Stable - $basearch
# baseurl=https://download.docker.com/linux/fedora/$releasever/$basearch/stable 
baseurl=https://download.docker.com/linux/fedora/29/$basearch/stable
enabled=1
gpgcheck=1
gpgkey=https://download.docker.com/linux/fedora/gpg
 ``

**Comment by bweston92** [comment]
Still struggling to get it working just from the docs though. https://docs.docker.com/install/linux/docker-ce/fedora/

**Comment by wohlben** [comment]
the documentation clearly states that fedora 28 and 29 are the only supported versions at the moment @bweston92 .
 
either wait or use a workaround as we did.

**Comment by bweston92** [comment]
@wohlben you're correct, sorry I skipped straight past that and started doing my usual workflow of copy and pasting the commands I usually take from the page.

**Comment by jscurtu** [comment]
all you need:

`sudo dnf config-manager --set-enabled docker-ce-test`

you can also disable the stable branch if you get annoyed by the dnf ignore warning.

`sudo dnf config-manager --set-disabled docker-ce-stable`

thats what I used after upgrading to Fedora 30 from 29 using dnf.

**Comment by mhitza** [comment]
@jscurtu If you already had previously installed the packages, because `containerd.io` is missing from both test and nightly

**Comment by jscurtu** [comment]
@mhitza right.. didnt think of that one thanks. 👍

**Comment by claysauruswrecks** [comment]
![gucci](https://media.giphy.com/media/xUPGGecEPwf2TXGz84/source.gif)

**Comment by ggobbe** [comment]
Is there something still blocking stable docker packages for Fedora 30?
What needs to be changed/updated to provide these packages?

**Comment by seemethere** [comment]
Yup there is a plan to release `containerd` packages for Fedora 30 soon, will update on a timeline but expect it within the next couple of weeks.

**Comment by cyfrost** [comment]
Don't want to spam the thread but this needs to be resolved quick. I mean, it's not like 6 months later a release pops up out of the blue and nobody has time. The development was in the open all along so I'd wonder what's blocking Docker's release cadences from aligning with Fedora's. Don't mean to come across as rude or something, just genuinely curious. For example, I've seen this happen with WineHQ too, they haven't released F30 builds yet so.

**Comment by claysauruswrecks** [comment]
@cyfrost - I mean, it's not like you can't speed up open source projects by paying people money to work on things you find important.

**Comment by cyfrost** [comment]
@claysauruswrecks No that wasn't my intent behind the "rant". Isn't it in the good interest of thr Docker devs/maintainers/community to make releases align?

**Comment by Pazns** [comment]
@claysauruswrecks
Well, we are talking about Docker Inc., which is no poor bearded dude in a basement. 
Either, Fedora is no weird copycat distro lying in a dark corner of internet. 
While I agree with the idea, I don't think it applies here. 

However, I honestly don't know how much work it would have been to port the then-current version of the docker ecosystem ahead of time for the release of Fedora 30.
I think I may not realise what it involves.

**Comment by dbronecki** [comment]
For now I'm using `moby-engine` package on Fedora 30. It seems to be working perfectly fine.

**Comment by jhford** [comment]
I've filed the issue for Fedora 31 preemptively today.

**Comment by basvandenbrink** [comment]
I agree with @Pazns and @dbronecki. We are now kinda forced to seek alternatives (and there are multiple nowadays) only because the packages are not released on time...

**Comment by luisnabais** [comment]
I think this delay is related to the way Fedora and Red Hat are running away from Docker and directing to Podman, Buildah, Skopeo and Kubernetes/Openshift.

**Comment by Pazns** [comment]
@luisnabais Interesting.
Is there any official sources about this ?

**Comment by luisnabais** [comment]
@Pazns I guess this is just an interpretation.
I've noticed on the last versions of Fedora, the Docker official packages for each latest version of Fedora are released at least some weeks after the Fedora final release, when on Debian 10 and Ubuntu 19.04 they are released early, even before the final version of the Linux distribuition is released.
Also, the number of articles on official Red Hat and Fedora related websites about using Podman/Buildah/Skopeo or containers without Docker are really high.

Examples:
https://developers.redhat.com/blog/2018/11/20/buildah-podman-containers-without-daemons/
https://developers.redhat.com/blog/2018/11/29/managing-containerized-system-services-with-podman/
https://developers.redhat.com/blog/2019/02/21/podman-and-buildah-for-docker-users/

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/managing_containers/finding_running_and_building_containers_without_docker

https://fedoramagazine.org/fedora-classroom-building-container-images-with-buildah/

**Comment by jpcaparas** [comment]
While `moby-engine` works for some people, it does not for me. One of my containers is maxing out system resources and grinding my machine to a halt (even with `cgroups` slices).

![Screenshot from 2019-05-13 16-32-15](https://user-images.githubusercontent.com/2406808/57596626-b6e19e00-759f-11e9-9c09-053f0c45d655.png)

I had to use the the `containerd.io` package from F28 (to quell dependency issues) and installed the  `docker` and `docker-cli` test builds. Problem solved.

**Comment by Pazns** [comment]
@luisnabais
Thanks for the resources!

@jpcaparas
Try using docker-ce from Docker repo with a - -releasever=29 option.

**Comment by aric49** [comment]
> @luisnabais
> Thanks for the resources!
> 
> @jpcaparas
> Try using docker-ce from Docker repo with a - -releasever=29 option.
Worked for me on Fedora 30.    When the release of docker drops for Fedora 30, will dnf automatically upgrade the fedora 29 version in favor of Fedora 30 stable?

**Comment by rickatnight11** [comment]
Yes, as the Fedora 30 release will also be a newer version of the package.

It works the same way if you upgrade an existing Fedora install with an existing Docker installation to a new release. Your installed Docker continues to function and seamlessly receives updates as soon as the new repo becomes available.

**Comment by aric49** [comment]
@rickatnight11  -- Fantastic.   I think that should be added to the Docker documentation at: https://docs.docker.com/install/linux/docker-ce/fedora/   wording to the effect of:

```
At this time newer versions of Fedora may not be supported right away. To install Docker for an older release of Fedora use DNF with a lower Fedora release number:

sudo dnf install --releasever=29 docker-ce docker-ce-cli containerd.io
```

**Comment by stklcode** [comment]
> I think that should be added to the Docker documentation [...] Thoughts?

It is not officially supported in terms of a stable, tested release. So why should a hack like this (which is the first thing that comes to my mind to deal with the "problem" anyway) be mentioned in the official docs?

It's a calculated risk to install from the previous release's repo. It worked well in the past and so it does with F29/30 and that's probably fine for _most_ cases. But has to be carefully considered before updating or setting up productive systems (applies to various other repos and systems as well)

**Comment by mccheesy** [comment]
> Yup there is a plan to release `containerd` packages for Fedora 30 soon, will update on a timeline but expect it within the next couple of weeks.

Any update on this?

**Comment by rux616** [comment]
> > I think that should be added to the Docker documentation [...] Thoughts?
> 
> It is not officially supported in terms of a stable, tested release. So why should a hack like this (which is the first thing that comes to my mind to deal with the "problem" anyway) be mentioned in the official docs?
> 
> It's a calculated risk to install from the previous release's repo. It worked well in the past and so it does with F29/30 and that's probably fine for _most_ cases. But has to be carefully considered before updating or setting up productive systems (applies to various other repos and systems as well)

I totally agree that it's a calculated risk, but I would also argue that in the absence of on-time release support, this verbiage *should* be added to the official docs. That being said, I believe it should also include a very plainly-stated warning that this is indeed a hack and should be taken with all caveats therein, for example that you shouldn't do this for anything critical or production-related, nor should you expect it to work 100% of the time.

**Comment by Nhoya** [comment]
Any news on that?

**Comment by nicolasmure** [comment]
As stated by @dbronecki [1], and briefly explained in an other thread [2], fedora no longer ships `docker-ce` package but ships `moby-engine` instead, which provides the docker binary and daemon.

___
[1] https://github.com/docker/for-linux/issues/600#issuecomment-491258266
[2] https://github.com/projectatomic/docker/issues/287#issuecomment-470912623

**Comment by stklcode** [comment]
Just to mention, `moby-engine` ships 18.06 with the stable package as of today and 18.09 for testing[1].
So if you just need any stable Docker engine it's fine. If the latest release is required now, you're gonna run into the same issue again.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1708133

**Comment by aric49** [comment]
> > > I think that should be added to the Docker documentation [...] Thoughts?
> > 
> > 
> > It is not officially supported in terms of a stable, tested release. So why should a hack like this (which is the first thing that comes to my mind to deal with the "problem" anyway) be mentioned in the official docs?
> > It's a calculated risk to install from the previous release's repo. It worked well in the past and so it does with F29/30 and that's probably fine for _most_ cases. But has to be carefully considered before updating or setting up productive systems (applies to various other repos and systems as well)
> 
> I totally agree that it's a calculated risk, but I would also argue that in the absence of on-time release support, this verbiage _should_ be added to the official docs. That being said, I believe it should also include a very plainly-stated warning that this is indeed a hack and should be taken with all caveats therein, for example that you shouldn't do this for anything critical or production-related, nor should you expect it to work 100% of the time. (And also that you are effectively going 'off book' at that point, so official support is going to be non-existent and even unofficial support will likely be thin.)

`moby-engine` is probably great for the vast majority of users looking to get a stable, relatively recent version of the Docker engine up and running on their fedora laptops.  It seems to be like it's essentially the Fedora equivalent of `docker.io` package in Ubuntu.   However, I'm not quite following the logic in the decision to not add a few sentences disclaimer advising Fedora users that docker-ce packages are likely releasing significantly later than the Fedora release schedule.  If users want to use docker-ce, then they should install the version for the previous Fedora distro, or install the `moby-engine` package.  I feel like it's a harmless addition to the documentation that clears up questions and gives users a work around until the distro-specific packages drop.  As @rux616  mentions, plainly stating it's a work around ensures that it's not a officially supported solution by Docker.  It's either that, or build packages that drop with the Fedora release schedule.  This way, you won't have GitHub issues opening every time a Fedora release drops :+1:

**Comment by seemethere** [comment]
Hello everyone here,

Sorry for the delayed update but the `containerd.io` package has been uploaded for Fedora 30 on the test channel.

If you'd like to try the upcoming release on Fedora 30 feel free to use the convenience script to install:

```
curl -fsSL get.docker.com | CHANNEL=test sh
```

**Comment by LucasCalazans** [comment]
It worked like a charm, thanks @seemethere 

> ```
> curl -fsSL get.docker.com | CHANNEL=test sh
> ```

**Comment by chrisckc** [comment]
It seems that containerd.io is now released but docker-ce and docker-ce-cli are still not:

```
$dnf list docker-ce
Last metadata expiration check: 0:08:46 ago on Thu 04 Jul 2019 11:19:37 BST.
Error: No matching Packages to list    
```

```
$dnf list containerd.io
Last metadata expiration check: 0:08:30 ago on Thu 04 Jul 2019 11:19:37 BST.
Available Packages
containerd.io.x86_64 
```

```
$dnf list docker-ce-cli
Error: No matching Packages to list
```

Used the script as suggested above instead:
`curl -fsSL get.docker.com | CHANNEL=test sh`

What would be the best way of updating to stable channel once it is released?

**Comment by AkihiroSuda** [comment]
Here is a workaround:

```
$ podman run -d --name dinp --privileged -v /run/dinp:/var/run -v /var/lib/dinp:/var/lib/docker docker:dind dockerd -H unix:///var/run/docker.sock
$ ln -s /run/dinp/docker.sock /var/run/docker.sock
$ podman exec dinp cat /usr/local/bin/docker > /usr/local/bin/docker
$ chmod +x /usr/local/bin/docker
```

**Comment by luisnabais** [comment]
It's not the same. Podman is still very inferior. It doesn't even allow for Docker Compose integration.

**Comment by localleon** [comment]
It seem's like this is fixed! The Docker-CE Repository on Fedora 30 provides me with: 
`containerd.io.x86_64                                         1.2.6-3.3.fc30                         @docker-ce-stable` and 
`docker-ce.x86_64                                      3:18.09.5-3.fc29                              @docker-ce-stable`

**Comment by UnR34L** [comment]
@localleon You sure ?

I still only see containerd in stable.

https://download.docker.com/linux/fedora/30/x86_64/stable/Packages/

**Comment by djanjic** [comment]
+1

Still can’t see packages.

**Comment by stklcode** [comment]
@localleon 
You obviously got a mixed setup, F30 containerd.io and F29 Docker CE
> containerd.io.x86_64 1.2.6-3.3.**fc30** @docker-ce-stable
> docker-ce.x86_64 3:18.09.5-3.**fc29** @docker-ce-stable

When installing on a blank system, complete stable stack is still not available from this repo (ant btw. 18.09.7 is the latest stable, not .5)

**Comment by rickatnight11** [comment]
Fedora 30 stable packages now available:

https://download.docker.com/linux/fedora/30/x86_64/stable/Packages/

**Comment by lucasvieira-bpp** [comment]
How to migrate test version to stable?

**Comment by lucassantosninb** [comment]
How to migrate test version to stable? I'm using repo.

**Comment by rickatnight11** [comment]
That depends on how you switched to the `test` repo, but looking at my `/etc/yum.repos.d/docker-ce.repo` repo config, I see there are already repos for both `test` and `stable`.  Just make sure that the `stable` repo has `enabled=1` (and `test` has `enabled=0`), and you should be set.

Ultimately this is the only config you need:

```
[docker-ce-stable]
name=Docker CE Stable - $basearch
baseurl=https://download.docker.com/linux/fedora/$releasever/$basearch/stable
enabled=1
gpgcheck=1
gpgkey=https://download.docker.com/linux/fedora/gpg
```

**Comment by kostich** [comment]
This can be closed. There are stable packages for Fedora 30 for a couple of days now and you can get the latest Docker on Fedora 30 by following the [official page](https://docs.docker.com/install/linux/docker-ce/fedora/).
