### ISSUE TITLE
Unable to start docker container

### ISSUE THREAD

**Issue by vickymca2005** [docker/for-linux#911]
i am trying to run simple "docker run hello-world" it is throwing below error,

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"write /proc/self/attr/keycreate: permission denied\"": unknown.
> ERRO[0000] error waiting for container: context canceled

Any idea?

**Comment by sunilchikkud** [comment]
Try using this command it will work `sudo docker run hello-world`

**Comment by NullOranje** [comment]
It's an issue with selinux.  I'm having the same issue on RHEL7 running the kernel version` 3.10.0-1062.9.1.el7`.  Running on a previous version `3.10.0-1062.4.3.el7` does not cause the issue.

**Comment by vickymca2005** [comment]
@NullOranje well said. Thanks. Issue is resolved. I have to run below command,
sudo semanage permissive -a container_runtime_t

**Comment by paulgear** [comment]
I am seeing the same symptoms, which I originally raised as https://github.com/containerd/containerd/issues/3862 - the containerd folks seem to think it's an issue with the docker packaging.  It doesn't seem dependent upon the kernel version - downgrading containerd.io from 1.2.6+ to 1.2.5 is what solved it for me.

**Comment by cpuguy83** [comment]
Have you tried updating the `container-selinux` package? Could be an issue that the min version needs to be bumped.

**Comment by thaJeztah** [comment]
closing as it looks this one went stale

**Comment by paulgear** [comment]
Apologies for the lack of response.  This is still an issue on RHEL7 systems, on the latest kernel and latest container-selinux package.  I'm still running containerd.io 1.2.5 in order to work around the issue.

**Comment by thaJeztah** [comment]
What version of the selinux package is installed?

I don't have access to a RHEL7 system currently, but running on CentOS 7.6, I was able to install docker and run containers

```
sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
```

```
yum info container-selinux
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.hostnet.nl
 * extras: mirror.hostnet.nl
 * updates: mirror.hostnet.nl
Installed Packages
Name        : container-selinux
Arch        : noarch
Epoch       : 2
Version     : 2.119.2
Release     : 1.911c772.el7_8
Size        : 41 k
Repo        : installed
From repo   : extras
Summary     : SELinux policies for container runtimes
URL         : https://github.com/containers/container-selinux
License     : GPLv2
Description : SELinux policy modules for use with container runtimes.
```

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.27.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.795GiB
 Name: centos-s-1vcpu-2gb-ams3-01
 ID: 4YFM:YWI7:GM6P:7ZUU:Q6YS:BM4L:O3M7:57I2:5ETQ:XJV3:HNZV:E2VY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by paulgear** [comment]
@thaJeztah Thanks for the reply.  Here's the equivalent status output from my system.  The thing that jumps out to me is the difference in `container-selinux` versions.  Is there perhaps another repo I should have enabled?

```[paul02g@aunot14267 ~]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
[paul02g@aunot14267 ~]$ yum info container-selinux
Loaded plugins: changelog, etckeeper, langpacks, product-id, search-disabled-repos, subscription-manager
kubernetes                                                                                                                                                                                                 554/554
Installed Packages
Name        : container-selinux
Arch        : noarch
Epoch       : 2
Version     : 2.74
Release     : 1.el7
Size        : 37 k
Repo        : installed
Summary     : SELinux policies for container runtimes
URL         : https://github.com/projectatomic/container-selinux
License     : GPLv2
Description : SELinux policy modules for use with container runtimes.

[paul02g@aunot14267 ~]$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 81
  Running: 0
  Paused: 0
  Stopped: 81
 Images: 780
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
 runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.19.1.el7.x86_64
 Operating System: Red Hat Enterprise Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.28GiB
 Name: aunot14267
 ID: JSXV:7E4K:VUDU:GOGC:FHBD:ZPHP:XYUB:5EQ3:CTNT:46OJ:G37T:JLJX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: paul02g
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```
