### ISSUE TITLE
Debian package containerd 1.2.12-1 listed but missing on the repository

### ISSUE THREAD

**Issue by tomlaredo** [docker/for-linux#930]
* [x] This is a bug report
* [ ] This is a feature request
* [x] I searched existing issues before opening this one

The package containerd.io_1.2.12-1_amd64.deb is listed but missing from Docker's repository for Debian Buster (10.3).

```
docker-01:~# cat /etc/apt/sources.list.d/docker.list 
deb https://download.docker.com/linux/debian buster stable
```
```
docker-01:~# apt update
Hit:1 http://ftp.fr.debian.org/debian-security buster/updates InRelease
Hit:2 http://ftp2.fr.debian.org/debian buster InRelease                  
Hit:3 http://ftp2.fr.debian.org/debian buster-updates InRelease                                                            
Hit:4 http://repo.saltstack.com/py3/debian/10/amd64/latest buster InRelease                                                
Get:5 https://download.docker.com/linux/debian buster InRelease [44.4 kB]                                 
Fetched 44.4 kB in 1s (43.3 kB/s)                     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.
```
```
docker-01:~# apt list --upgradable
Listing... Done
containerd.io/buster 1.2.12-1 amd64 [upgradable from: 1.2.10-3]
docker-ce-cli/buster 5:19.03.6~3-0~debian-buster amd64 [upgradable from: 5:19.03.5~3-0~debian-buster]
docker-ce/buster 5:19.03.6~3-0~debian-buster amd64 [upgradable from: 5:19.03.5~3-0~debian-buster]
```
```
docker-01:~# apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  containerd.io docker-ce docker-ce-cli
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 20.1 MB/85.5 MB of archives.
After this operation, 630 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 https://download.docker.com/linux/debian buster/stable amd64 containerd.io amd64 1.2.12-1
  404  Not Found [IP: 13.227.220.33 443]
E: Failed to fetch https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/containerd.io_1.2.12-1_amd64.deb  404  Not Found [IP: 13.227.220.33 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
```
docker-01:/home/tom# apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

**Comment by tomlaredo** [comment]
Linked to:
-  https://github.com/docker/for-linux/issues/816
-  https://github.com/docker/for-linux/issues/901

**Comment by arkodg** [comment]
relates to https://github.com/moby/moby/issues/40514#issuecomment-586054841

**Comment by kamild1996** [comment]
I'm trying to install Docker on Raspbian Buster and I'm getting this error.
Running @tiborvass's command: `service docker stop && service containerd stop && apt purge containerd.io docker-ce docker-ce-cli && rm -f /etc/apt/sources.list.d/docker.list && curl -fsSL https://get.docker.com/ | sh`
results in:
`E: Failed to fetch https://download.docker.com/linux/debian/dists/buster/pool/stable/armhf/containerd.io_1.2.12-1_armhf.deb  404  Not Found [IP: 54.230.228.63 443]`

I guess I have to wait for this to get fixed?

**Comment by tiborvass** [comment]
Sorry about that. Can you try again? Should be fixed.

**Comment by kamild1996** [comment]
> @tomlaredo @kamild1996 Sorry about that. Can you try again? Should be fixed.

Now it installed without any hiccups, thank you <3

**Comment by tiborvass** [comment]
Thanks. Closing. If someone still sees this error let me know.

**Comment by wolfgangpfnuer** [comment]
about a third of my servers are seeing version 1.2.10-3 as the newest version, the other 2/3 are seeing 1.2.12-1 as the newest version... Guess this is not fixed yet

**Comment by wolfgangpfnuer** [comment]
I think that it might actually be a different problem, so I've created a new issue for this.
https://github.com/docker/for-linux/issues/946

**Comment by vinayus** [comment]
+1 for Centos as well.
Also my kubernetes cluster becomes unstable if containerd is manually upgraded to v1.2.12.

The default binary which comes along docker(v1.2.10) seems to be stable
